root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/acapulko ."
  entrypoint = ["./tmp/acapulko"]
  delay = 1000
  exclude_dir = ["tmp", "vendor", "node_modules", ".git", "bin", "static"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "html", "tmpl"]
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500
  log = "tmp/build-errors.log"
  rerun = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false
  main_only = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
